### ISSUE TITLE
Update to use Monitoring::Plugin

### ISSUE THREAD

**Issue by andibing** [device42/Device42-Nagios-Health-Check#3]
Nagios::Plugin appears to be have been replaced by Monitoring:Plugin. 
http://search.cpan.org/~nierlein/Monitoring-Plugin-0.39/lib/Monitoring/Plugin.pm

Please can you review an update accordingly.

**Comment by bitgreg** [comment]
@andibing sorry for the delay on this, should be set now. Please let us know if you have trouble.
